services:
  mysql:
    image: mysql:8.4
    container_name: library-pos-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_pos
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_pass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci

volumes:
  mysql_data:
