#Library POS Settings
#Sun Mar 22 07:00:06 EET 2026
quick.F1=123
quick.F2=
quick.F3=
quick.F4=
quick.F5=
quick.F6=
quick.qty.F1=3
quick.qty.F2=1
quick.qty.F3=1
quick.qty.F4=1
quick.qty.F5=1
quick.qty.F6=1
