# MySQL profile configuration
spring.datasource.url=jdbc:mysql://localhost:3308/library_pos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=library_user
spring.datasource.password=library_pass
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Optional: show SQL while developing
spring.jpa.show-sql=false
