# MySQL profile configuration
spring.datasource.url=jdbc:mysql://100.104.141.62:3306/library_pos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=Ramy
spring.datasource.password=1234
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Optional: show SQL while developing
spring.jpa.show-sql=true
